# Generated by Django 4.2 on 2023-04-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_do_it', models.CharField(max_length=40, verbose_name='Имя пользователя')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('note', models.TextField(verbose_name='Текст записи')),
            ],
        ),
    ]
